In [2]:
import pandas as pd

In [6]:
data = [1,2,3,4]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int64

In [38]:
s = pd.Series([10,20,30],index=["a","b","c"])
s.index.name= "My_list"# to name series (name.index.name = (Name ))
print(s)
s.name
s.index=[1,2,3]# to updaet index
print(s)
s.values# to show the value of series return array
print(s.max())
print(s.index)

My_list
a    10
b    20
c    30
dtype: int64
1    10
2    20
3    30
dtype: int64
30
Index([1, 2, 3], dtype='int64')

In [21]:
import numpy as np # if we want to know the ave we need to first imoprt the library then compute the mean
ave = np.mean(s)
print(ave)

20.0

In [39]:
s[1]#to print the value from index (after updat index with (1,2,3) we now use it)

np.int64(10)

In [41]:
s[s<=20] #print using condition

1    10
2    20
dtype: int64

In [46]:
2 in s # to check from index if it there or not

True

In [47]:
dic = s.to_dict() # convert series to dict key:index and value: data of the series
dic

{1: 10, 2: 20, 3: 30}

In [50]:
s1 = pd.Series(dic) #to conver from dict to series 
s1

1    10
2    20
3    30
dtype: int64

In [55]:
countriesPop = pd.Series([
8700000,
4300000,
3000000,
2100000,np.nan], index = ['China','Germany','Japan','USA',"Oman"])
countriesPop.name = "countriesPop"

In [56]:
pd.isnull(countriesPop) # to check if all index don't have a vlaue

China      False
Germany    False
Japan      False
USA        False
Oman        True
Name: countriesPop, dtype: bool

In [57]:
pd.notnull(countriesPop) # to check if all index have a vlaue

China       True
Germany     True
Japan       True
USA         True
Oman       False
Name: countriesPop, dtype: bool

In [58]:
pd.isnull(countriesPop).sum() # to count number of null

np.int64(1)

In [59]:
countriesPop2 = pd.Series([
8700000,
4300000,
3000000,
2100000,500000], index = ['China','Germany','Japan','USA',"Oman"])
countriesPop2.name = "countriesPop"

In [60]:
countriesPop+countriesPop2

China      17400000.0
Germany     8600000.0
Japan       6000000.0
USA         4200000.0
Oman              NaN
Name: countriesPop, dtype: float64

In [66]:
grade = pd.Series({"Arabic":90,"Math":96,"Englis":80})
print("Mark grater than 80:\n",grade[grade>80])

Mark grater than 80:
 Arabic    90
Math      96
dtype: int64

In [68]:
s2 = pd.Series([10,None,30,None,50])
number_of_none = s2.isna().sum()
print("number_of_none",number_of_none)
mean_val = s2.mean()
s2=s2.fillna(mean_val)
print(s2)

number_of_none 2
0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
dtype: float64

In [72]:
name =pd.Series(["Ahmed","Maryam","Sarah","Ali"])
upper = name.str.upper() # str to accses string inside the series
print(upper)
print(name[name.str.len()>4])

0     AHMED
1    MARYAM
2     SARAH
3       ALI
dtype: object
0     Ahmed
1    Maryam
2     Sarah
dtype: object

In [83]:
s3 = pd.Series([10,50,30],index=["x","y","z"])
s3.rename(index={"x":"a"},inplace = True) # to replace it peremantaly
print(s3)
s3["b"]=25 # to add a new value: series name[index]=value
print(s3)
print(s3.sort_values())
print(s3.value_counts())

a    10
y    50
z    30
dtype: int64
a    10
y    50
z    30
b    25
dtype: int64
a    10
b    25
z    30
y    50
dtype: int64
10    1
50    1
30    1
25    1
Name: count, dtype: int64

In [85]:
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([15, 15, 35])
print(s1>s2)

0    False
1     True
2    False
dtype: bool

In [86]:
sales = pd.Series([200, 450, 300, 150, 500],
                  index=["Mon", "Tue", "Wed", "Thu", "Fri"])

# Total sales
print("Total:", sales.sum())

# Average sales
print("Average:", sales.mean())

# Max sales day
print("Highest day:", sales.idxmax())

# Sales > 300
print("Days with sales > 300:")
print(sales[sales > 300])

Total: 1600
Average: 320.0
Highest day: Fri
Days with sales > 300:
Tue    450
Fri    500
dtype: int64

In [87]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}
df =pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [89]:
df.head() #by defualt it retuen first5 but if we write vaue inside ()

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [90]:
df.tail(1)#by defualt it retuen last 5 but if we write vaue inside ()

      Name  Age     City
2  Charlie   22  Chicago

In [91]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

In [94]:
print(df.describe())

             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

In [96]:
print(df["Name"])
print(df[["Name","City"]])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [97]:
print(df.loc[0]) #First row
print(df.iloc[1])#Row with index 1 , for example if my index is abc [] write it name

Name       Alice
Age           24
City    New York
Name: 0, dtype: object
Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object

In [98]:
pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.19-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\dell\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\dell\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\dell\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\dell\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\dell\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.19-py3-none-any.whl (208 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.0 kagglesdk-0.1.19
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\Dell\AppData\Local\Temp\ipykernel_3816\874124.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87
1           5    Tokyo   24         99           95            89
2           6   Berlin   22         72           70            99
3           7   London   23         97           90            74
4           8    Tokyo   22         91           71            79

   power_bi_marks  english_marks
0              82             75
1              86             82
2              79             77
3              72             85
4              80             75

In [3]:
df.head()

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75

In [106]:
df.tail()

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,London,22,85,87,93,70,86

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      497 non-null    int64
 1   location        497 non-null    object
 2   age             497 non-null    int64
 3   sql_marks       497 non-null    int64
 4   excel_marks     497 non-null    int64
 5   python_marks    497 non-null    int64
 6   power_bi_marks  497 non-null    int64
 7   english_marks   497 non-null    int64
dtypes: int64(7), object(1)
memory usage: 31.2+ KB

In [105]:
df.describe()

,student_id,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
count,497.000000,497.000000,497.000000,497.000000,497.000000,497.000000,497.000000
mean,252.000000,21.380282,84.661972,85.384306,85.388330,84.545272,84.824950
std,143.615807,2.205714,8.745415,8.782497,8.878668,8.903066,9.060479
min,4.000000,18.000000,70.000000,70.000000,70.000000,70.000000,70.000000
25%,128.000000,20.000000,78.000000,78.000000,77.000000,77.000000,77.000000
50%,252.000000,21.000000,85.000000,86.000000,86.000000,84.000000,85.000000
75%,376.000000,23.000000,92.000000,93.000000,94.000000,92.000000,93.000000
max,500.000000,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [113]:
df['location'].unique()

array(['Sydney', 'Tokyo', 'Berlin', 'London', 'Toronto', 'Melbourne',
       'Paris', 'Los Angeles', 'New York'], dtype=object)

In [115]:
df['location'].value_counts() #number of stud from diff location

array([60, 58, 57, 56, 55, 53, 52, 46])

In [117]:
df['sql_marks'].mean() # ave mark of sql course

np.float64(84.66197183098592)

In [5]:
df.iloc[1:6] #retrive through

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
5,9,Toronto,20,93,88,75,93,72

In [6]:
df.iloc[[1,6]]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
6,10,Tokyo,18,77,87,100,98,93

In [7]:
df.iloc[1:6,0:2]

   student_id location
1           5    Tokyo
2           6   Berlin
3           7   London
4           8    Tokyo
5           9  Toronto

In [17]:
df.iloc[0:20,7]

np.float64(84.0)

In [18]:
df.iloc[0:20,7].mean()

np.float64(84.0)